apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: elastalert
subjects:
- kind: ServiceAccount
  name: elastalert
  namespace: kube-elastalert
roleRef:
  kind: ClusterRole
  name: elastalert
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: elastalert
  labels:
    k8s-app: elastalert
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastalert
  namespace: kube-elastalert
  labels:
    k8s-app: elastalert
