apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastalert
  namespace: kube-elastalert
  labels:
   k8s-app: elastalert
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elastalert
  template:
    metadata:
      labels:
        k8s-app: elastalert
    spec:
      serviceAccountName: elastalert
      containers:
      - name: elastalert
        image: rdrg/elastalert-docker:0.1.39
        volumeMounts:
        - name: config
          mountPath: /opt/config
        - name: rules
          mountPath: /opt/rules
      volumes:
        - name: rules
          configMap:
            name: logstash-rule
        - name: config
          configMap:
            name: elast-config
